version: '3'
services:
  web:
      build: ./backend
      #workspace: app/backend
      #command: bundle exec rails s -p 3000 -b '0.0.0.0'
      volumes:
        - ./backend:/app/backend
      ports:
        - "3005:3000"
      environment:
        - "DATABASE_HOST=db"
        - "DATABASE_PORT=5432"
        - "DATABASE_USER=postgres"
        - "DATABASE_PASSWORD=password"
      links:
        - db
      stdin_open: true

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      